"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$directory\
$git_branch\
$git_status\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$lua\
$docker_context\
$character"""

add_newline = false

# username module
[username]
show_always = true
style_user = "fg:#a1a1aa"
style_root = "fg:#f87171"
format = '[$user]($style)'

# directory module
[directory]
style = "fg:#e4e4e7"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# git branch module
[git_branch]
symbol = ""
style = "fg:#e4e4e7"
format = '[[ $symbol $branch ](fg:#e4e4e7)]($style)'

# git status module
[git_status]
style = "fg:#71717a"
format = '[[($all_status$ahead_behind )](fg:#71717a)]($style)'

# nodejs module
[nodejs]
symbol = "󰎙"
style = "fg:#a1a1aa"
format = '[[ $symbol( $version) ](fg:#a1a1aa)]($style)'

# c module
[c]
symbol = ""
style = "fg:#a1a1aa"
format = '[[ $symbol( $version) ](fg:#a1a1aa)]($style)'

# rust module
[rust]
symbol = ""
style = "fg:#a1a1aa"
format = '[[ $symbol( $version) ](fg:#a1a1aa)]($style)'

# go module
[golang]
symbol = "󰟓"
style = "fg:#a1a1aa"
format = '[[ $symbol( $version) ](fg:#a1a1aa)]($style)'

# php module
[php]
symbol = ""
style = "fg:#a1a1aa"
format = '[[ $symbol( $version) ](fg:#a1a1aa)]($style)'

# java module
[java]
symbol = ""
style = "fg:#a1a1aa"
format = '[[ $symbol( $version) ](fg:#a1a1aa)]($style)'

# kotlin module
[kotlin]
symbol = ""
style = "fg:#a1a1aa"
format = '[[ $symbol( $version) ](fg:#a1a1aa)]($style)'

# haskell module
[haskell]
symbol = ""
style = "fg:#a1a1aa"
format = '[[ $symbol( $version) ](fg:#a1a1aa)]($style)'

# python module
[python]
symbol = ""
style = "fg:#a1a1aa"
format = '[[ $symbol( $version) ](fg:#a1a1aa)]($style)'

# lua module
[lua]
symbol = "󰢱"
style = "fg:#a1a1aa"
format = '[[ $symbol( $version) ](fg:#a1a1aa)]($style)'

# docker context module
[docker_context]
symbol = "󰡨"
style = "fg:#71717a"
format = '[[ $symbol( $context) ](fg:#71717a)]($style)'

# line break module
[line_break]
disabled = true

# character module
[character]
format = "[](fg:#e4e4e7) "
