/*
  Hyprland Desktop Module

  Configures Hyprland, GTK/cursor theming, gammastep, and polkit. Deploys the full
  Lua config tree to ~/.config/hypr/ (generated variables/scheme + symlinked sources).

  Exposes:
    - nesw.desktop.hyprland.terminal
    - nesw.desktop.hyprland.browser
  Depends: modules/themes; flake input hyprland; modules/desktop/quickshell (systemd)
*/
{ config, lib, pkgs, ... }:
let
  inherit (lib) mkOption types mkDefault;
  cfg = config.nesw.desktop.hyprland;
  theme = config.nesw.theme;

  schemeLua = ''
    -- baseline palette (generated from nesw.theme.colors)
    return {
        primary = "${theme.colors.primary}",
        onSurfaceVariant = "${theme.colors.onSurfaceVariant}",
        surface = "${theme.colors.surface}",
        surfaceContainer = "${theme.colors.surfaceContainer}",
    }
  '';

  variablesLua = ''
    -- Generated by NixOS - override via nesw.desktop.hyprland options
    local scheme = require("scheme.current")

    return {
        -- apps
        terminal = "${cfg.terminal}",
        browser = "${cfg.browser}",

        -- touchpad
        touchpadDisableTyping = false,
        touchpadScrollFactor = 0.4,
        gestureFingers = 3,
        workspaceSwipeFingers = 4,
        gestureFingersMore = 4,

        -- blur
        blurEnabled = true,
        blurSpecialWs = false,
        blurPopups = true,
        blurInputMethods = true,
        blurSize = 8,
        blurPasses = 2,
        blurXray = false,

        -- shadow
        shadowEnabled = false,
        shadowRange = 10,
        shadowRenderPower = 2,
        -- shadowColor = "rgba(" .. scheme.surface .. "d4)",

        -- gaps
        -- the 4px screen border sits inside gaps_out, so the visible gap between
        -- windows and the border/notch is (windowGapsOut - 4) on all sides
        workspaceGaps = 18,
        windowGapsIn = 4,
        windowGapsOut = 18,
        singleWindowGapsOut = 24,

        -- window styling
        windowOpacity = 0.95,
        windowRounding = 15,
        windowBorderSize = 2,
        activeWindowBorderColor = "rgba(" .. scheme.primary .. "e6)",
        inactiveWindowBorderColor = "rgba(" .. scheme.onSurfaceVariant .. "11)",

        -- misc
        volumeStep = 5,
        cursorTheme = "Bibata-Modern-Ice",
        cursorSize = 20,
        suspendCommand = "systemctl suspend",

        -- keybinds
        -- workspaces
        kbMoveWinToWs = "SUPER + CTRL",
        kbMoveWinToWsGroup = "SUPER + CTRL + SHIFT + ALT",
        kbGoToWs = "SUPER",
        kbGoToWsGroup = "SUPER + CTRL + ALT",
        kbNextWs = "CTRL + SUPER + Right",
        kbPrevWs = "CTRL + SUPER + Left",
        kbNextWsMouse = "SUPER + mouse_down",
        kbPrevWsMouse = "SUPER + mouse_up",
        kbNextWsGroupMouse = "CTRL + SUPER + mouse_down",
        kbPrevWsGroupMouse = "CTRL + SUPER + mouse_up",
        kbMoveWinNextWsMouse = "SUPER + ALT + mouse_down",
        kbMoveWinPrevWsMouse = "SUPER + ALT + mouse_up",
        kbToggleSpecialWs = "SUPER + S",

        -- window groups
        kbWindowGroupCycleNext = "ALT + Tab",
        kbWindowGroupCyclePrev = "SHIFT + ALT + Tab",
        kbUngroup = "SUPER + U",
        kbToggleGroup = "SUPER + Comma",

        -- window actions
        kbMoveWindow = "SUPER + Z",
        kbResizeWindow = "SUPER + X",
        kbWindowPip = "SUPER + ALT + backslash",
        kbPinWindow = "SUPER + P",
        kbWindowFullscreen = "SUPER + F",
        kbWindowBorderedFullscreen = "SUPER + ALT + F",
        kbToggleWindowFloating = "SUPER + ALT + space",
        kbCloseWindow = "SUPER + Q",

        -- apps
        kbTerminal = "SUPER + Return",
        kbBrowser = "SUPER + W",
        kbLauncher = "SUPER + space",
        kbScreenshot = "SUPER + SHIFT + S",

        -- misc
        kbSession = "CTRL + ALT + Delete",
    }
  '';

  hyprSrc = lib.cleanSourceWith {
    src = ./.;
    filter = path: type:
      let
        name = baseNameOf path;
      in
        !(name == "default.nix" || name == "README.md");
  };

  hyprConfig = pkgs.runCommand "nesw-hyprland-config" { } ''
    mkdir -p $out/scheme
    cp -ra ${hyprSrc}/. $out/
    cat > $out/variables.lua <<'EOF'
${variablesLua}
EOF
    cat > $out/scheme/default.lua <<'EOF'
${schemeLua}
EOF
    cp $out/scheme/default.lua $out/scheme/current.lua
  '';
in
{
  options.nesw.desktop.hyprland = {
    terminal = mkOption {
      type = types.str;
      default = mkDefault "ghostty";
      description = "Default terminal emulator (keybind: Super+Return).";
    };

    browser = mkOption {
      type = types.str;
      default = mkDefault "zen-beta";
      description = "Default browser (keybind: Super+W).";
    };
  };

  config = {
    home.pointerCursor = {
      gtk.enable = true;
      x11.enable = true;
      package = pkgs.bibata-cursors;
      name = "Bibata-Modern-Ice";
      size = 20;
    };

    gtk = {
      enable = true;
      cursorTheme = {
        package = pkgs.bibata-cursors;
        name = "Bibata-Modern-Ice";
        size = 20;
      };
    };

    wayland.windowManager.hyprland = {
      enable = true;
      package = null;
      portalPackage = null;
    };

    xdg.configFile.hypr = {
      source = hyprConfig;
      recursive = true;
      force = true;
    };

    # autostart deps (see config/execs.lua)
    home.packages = with pkgs; [
      wl-clipboard # wl-paste
      cliphist # clipboard history
      trash-cli # trash-empty
      glib # gsettings
    ];

    # polkit auth agent (hyprland has no DE to autostart one)
    systemd.user.services.polkit-gnome-authentication-agent-1 = {
      Unit = {
        Description = "polkit-gnome-authentication-agent-1";
        WantedBy = [ "graphical-session.target" ];
        Wants = [ "graphical-session.target" ];
        After = [ "graphical-session.target" ];
      };
      Service = {
        Type = "simple";
        ExecStart = "${pkgs.polkit_gnome}/libexec/polkit-gnome-authentication-agent-1";
        Restart = "on-failure";
        RestartSec = 1;
        TimeoutStopSec = 10;
      };
    };

    # night light (uses system geoclue2 for location)
    services.gammastep = {
      enable = true;
      provider = "geoclue2";
      temperature = {
        day = 5500;
        night = 3700;
      };
    };
  };
}
